### ISSUE TITLE
accessToken 관련 안내문

### ISSUE THREAD

**Issue by wonsuyon** [JosephNK/flutter_kakao_login#1]
좋은 package 제작 감사합니다
잘 작동하네요

로그인 후 토큰을 서버로 보내 인증이 필요한데
토큰을 가져올수있도록 구현을 해 두시고
관련 안내가 없네요

var accessToken = (await kakaoSignIn.currentAccessToken).token;

이렇게 진행하면 맞나요

**Comment by JosephNK** [comment]
네! 그렇게 사용하시면 됩니다~
AccessToken 안내에 대해서는 업데이트 해놓겠습니다!

**Comment by JosephNK** [comment]
@wonsuyon 참고로 저는 아래와 같이 작성하여 테스트 해보았습니다.

```
Future<Null> _getAccessToken() async {
    final KakaoAccessToken accessToken = await (kakaoSignIn.currentAccessToken);
    if (accessToken != null) {
        final token = accessToken.token;
        // Todo Someting...
    }
}
```
