### ISSUE TITLE
D8: Type com.google.android.gms.common.internal.zzf is referenced as an interface from `com.google.android.gms.internal.zzcms`.

### ISSUE THREAD

**Issue by rocky-concetto** [JosephNK/flutter_kakao_login#12]
I m getiing the above issue , while trying to run in android, so please let me know solution

**Comment by JosephNK** [comment]
@rocky-concetto 

Hi, rocky-concetto!
I think the issue is related to Firebase or FCM.  
Please explain it in more detail.

**Comment by rocky-concetto** [comment]
Hello, thank you for reply , i have not integrate firebase Or FCM , when i install kakao plugin the issue occurs

**Comment by JosephNK** [comment]
If you create an empty project and then run it after the Kakao plug-in install, does the message appear?
I'll check, too.

**Comment by rocky-concetto** [comment]
sure , plz let me check

**Comment by rocky-concetto** [comment]
I have check with empty demo but its now working , app is carshed ,without plugin demo works , please see the image,
Please help me to integrate in my app
![Screenshot_2019-07-31-15-24-09-973_com miui home](https://user-images.githubusercontent.com/41227766/62202995-f7370800-b3a7-11e9-94d4-4b39f9a65967.png)

**Comment by JosephNK** [comment]
@rocky-concetto 

I just tried it by creating a test app.

My test environment is as follows.
- Flutter 1.7.8+hotfix.4
- Android Studio 3.2.1
- Android emulator is 'Pixel (API 28)'

The test sequence is as follows.

- first test
```
$ flutter create flutter_app_kakao
$ flutter run
```
Result :  The default flutter app is working.

- next test
```
dependencies:
  flutter_kakao_login: "^0.3.0"
```
Add flutter_kakao_login dependencies to the pubspec.yaml file.
Refer to the flutter_kakao_login document and set kakao_strings.xml, AndroidManifest.xml.
```
$ flutter run
```
Result : App is working.

If crash error is [java.lang.NullPointerException: Argument 'cacheName' cannot be null], you must set kakao_strings.xml.
This is an sdk error in kakao.

ps) I don't have Android Mi Device so I can't test it. Sorry :(

**Comment by rocky-concetto** [comment]
Thanks , I have updated settings and works , but dont know why it can not run in my app

**Comment by rocky-concetto** [comment]
any update on issue?

**Comment by rocky-concetto** [comment]
I have run app on another system and its works
