### ISSUE TITLE
can not get email and profile of user in KakaoAccountResult

### ISSUE THREAD

**Issue by rocky-concetto** [JosephNK/flutter_kakao_login#13]
when we login in kakao and get KakaoAccountResult, there is only name and id , we are getting mail and proifle blank , even if we have that in our kakao account.

Please help

**Comment by JosephNK** [comment]
@rocky-concetto 

Hi, rocky-concetto

In case of email

First of all, you need to configure it in the Kakao console web page. 
You must switch it on to allow email.

Secondly, even if you set an email, you cannot receive it unless the user agrees.

See https://developers.kakao.com/

**Comment by rocky-concetto** [comment]
![Screenshot 2019-08-13 at 10 27 07 AM](https://user-images.githubusercontent.com/41227766/62916179-f1342480-bdb4-11e9-95ac-787bb7b03c7a.png)
![Screenshot 2019-08-13 at 10 26 56 AM](https://user-images.githubusercontent.com/41227766/62916180-f1342480-bdb4-11e9-961f-4f8d2e9da8cb.png)
see my settings in Kakao console web page, i have already allow email and profile ,

**Comment by JosephNK** [comment]
@rocky-concetto 

Hi, rocky-concetto!

Did the user choose to allow email when logging in to Kakao after launching the your app?

**Comment by rocky-concetto** [comment]
Yes, I allowed
