### ISSUE TITLE
build failed with use google maps plugin

### ISSUE THREAD

**Issue by anewgate** [JosephNK/flutter_kakao_login#18]
hi
Thank you for your effort.
I recently tried to build it for use with the google map plugin but it failed.
Help me.

=environment=======================================================
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.4 18E226, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)
=================================================================

[pubspec.yaml]
dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter: ^0.5.21+8
  flutter_kakao_login: ^0.5.0

=error=============================================================
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              1.1s
Resolving dependencies...                                           2.3s
Note: /Users/dongjinkim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_kakao_login-0.5.0/android/src/main/java/com/josephnk/flutterkakaologin/FlutterKakaoLoginPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
**R8: Type com.google.android.gms.common.internal.zzf is referenced as an interface from `com.google.android.gms.internal.zzcms`.**
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 55s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      56.5s
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
    To learn more, see: https://developer.android.com/studio/build/shrink-code
Gradle task assembleRelease failed with exit code 1
=================================================================

**Comment by fysoul17** [comment]
Have you tried adding firebase_analytics: ^5.0.10 in puspec.yaml? My case was resolved by adding it as I use firebase plugins and had the same error without an analytics package.
