### ISSUE TITLE
I've problem

### ISSUE THREAD

**Issue by anewgate** [JosephNK/flutter_kakao_login#2]
Dear JosephNK.
I have some problem.

It's my development environment.
flutter : 0.9.4
ide : Android studio

Also this is build console message.
======================================================================
Launching lib/main.dart on k7p in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 
Running pod install...
CocoaPods' output:
↳
      Preparing
    
    Analyzing dependencies
    
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    
    Finding Podfile changes
      A flutter_kakao_login
      - Flutter
      - flutter_facebook_login
      - shared_preferences
      - video_player
    
    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
    -> Fetching podspec for `flutter_kakao_login` from `.symlinks/plugins/flutter_kakao_login/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
    
    Resolving dependencies of `Podfile`
    
    Comparing resolved specification to the sandbox manifest
      A KakaoOpenSDK
      A flutter_kakao_login
      - Bolts
      - FBSDKCoreKit
      - FBSDKLoginKit
      - Flutter
      - flutter_facebook_login
      - shared_preferences
      - video_player
    
    Downloading dependencies
    
    -> Using Bolts (1.9.0)
    
    -> Using FBSDKCoreKit (4.36.0)
    
    -> Using FBSDKLoginKit (4.36.0)
    
    -> Using Flutter (1.0.0)
    
    -> Installing KakaoOpenSDK (1.8.2)
      > Copying KakaoOpenSDK from `/Users/mbp2018/Library/Caches/CocoaPods/Pods/Release/KakaoOpenSDK/1.8.2-c09b1` to `Pods/KakaoOpenSDK`
    
    -> Using flutter_facebook_login (0.0.1)
    
    -> Installing flutter_kakao_login (0.0.1)
    
    -> Using shared_preferences (0.0.1)
    
    -> Using video_player (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include static frameworks: (KakaoOpenSDK)
    
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:87:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `block in verify_no_static_framework_transitive_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in `each'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:36:in `validate!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:415:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:118:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
    
    [!] 'KakaoOpenSDK' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.
Finished with error: Error running pod install

please help me. ;(

**Comment by JosephNK** [comment]
@anewgate 

Hello :)

I do not know the exact reason, but it seems to be the http address problem.

```
$ cd /Users/[yourname]/.cocoapods/repos/master/Specs
$ find $. -type f -wholename "*1.8.0/KakaoOpenSDK.podspec.json"
   e.g,,
   ./c/f/1/KakaoOpenSDK/1.8.0/KakaoOpenSDK.podspec.json
$ vi ./c/f/1/KakaoOpenSDK/1.8.0/KakaoOpenSDK.podspec.json

"source": {
"http": "http://devrepo.kakao.com:8088/nexus/content/groups/public/com/kakao/sdk/KakaoOpenSDK/1.8.0/KakaoOpenSDK-1.8.0.zip"
}
```
change to address 'http://devrepo.kakao.com:8088/nexus/content/groups/public/com/kakao/sdk/KakaoOpenSDK/1.8.0/KakaoOpenSDK-1.8.0.zip' to 'https://devrepo.kakao.com:8088/nexus/content/groups/public/com/kakao/sdk/KakaoOpenSDK/1.8.0/KakaoOpenSDK-1.8.0.zip'

And try again.

See this link. => https://github.com/haxpor/Potatso/issues/104#issuecomment-423788675

##############

Note that!  Not related to the above. I try test and I did the following. I tested it with a simulator.

- Flutter 0.9.4
- cocoapods 1.5.3

```
$ flutter create myapp
$ cd myapp
$ vi pubspec.yaml
   dependencies:
       flutter_kakao_login: "^ 0.0.3"
$ flutter packages get
$ flutter run 
```
and it worked.

**Comment by JosephNK** [comment]
@anewgate 

I did the following.

```
$ flutter create myApp
$ cd myApp
$ vi pubspec.yaml
   dependencies:
       flutter_kakao_login: "^ 0.0.3"
$ flutter packages get
$ flutter run <~~ BUILD FILED
$ flutter run <~~ SUCCESS
```
and it worked.

**Comment by anewgate** [comment]
Sorry. it's not worked;
but I'm solved  temporary method.
I have commented out the **use_frameworks!** code in Podfile(line number 30 around).

Anyway Thank you so much.
