### ISSUE TITLE
Error when used with Firebase

### ISSUE THREAD

**Issue by iCodePoet** [JosephNK/flutter_kakao_login#20]
Error when used with Firebase
Errors only occur on Android.

It's okay to use it alone, but when using it with the Firebase, an error such as a picture occurs.

<img width="1130" alt="Screen Shot 2019-11-29 at 2 32 47 PM" src="https://user-images.githubusercontent.com/29420674/69846010-fbbbf080-12b5-11ea-96ff-ab1c3f575a5b.png">

**Comment by fysoul17** [comment]
You need a more specific explanation about the error.  
In my case, adding 'firebase_analytics' package solved the error.
