### ISSUE TITLE
unlink 버튼을 누르면 에러가 나네요.

### ISSUE THREAD

**Issue by Feelthewind** [JosephNK/flutter_kakao_login#22]
예제 올라온데로 돌렸는데 로그인 및 다른 기능은 문제가 없는데 unlink만 에러가 뜨네요.

java.lang.IllegalStateException: Reply already submitted 이렇게 나오는데 무슨 문제일까요?

**Comment by amondnet** [comment]
@Feelthewind

설정 하신 내용이나 코드를 알려주실 수 있을까요? 해당 로그만으로는 파악이 어렵습니다.

- flutter doctor -v 실행결과:
- simulator or real device?:
- code or steps to reproduce ( full steps to reproduce so that we can reproduce the problem. )
- flutter run --verbose 로 실행한 후 관련 log

등이 있으면 문제해결에 도움이 될거 같습니다.
