### ISSUE TITLE
Login Form UI 형태/색/한글

### ISSUE THREAD

**Issue by wangjacsi** [JosephNK/flutter_kakao_login#23]
로그인 화면 한글로 변경하려면 어떻게 하나요? 
화면 UI가 기본적으로 아래 UI인(첫번째 이미지) 것인가요? 
아래 두번째 화면 처럼 나오게 하려면 어떻게 하나요?
제목도 logIn이 아닌 두번째 처럼 카카오 로그인 으로 변경하려면 어떻게 하나요?

<img width="490" alt="스크린샷 2020-01-12 오전 12 35 38" src="https://user-images.githubusercontent.com/5095201/72206773-20ba9a80-34d5-11ea-8f25-adb3ad58092e.png">

<img width="627" alt="스크린샷 2020-01-12 오전 12 49 29" src="https://user-images.githubusercontent.com/5095201/72206804-768f4280-34d5-11ea-9431-c22732588e2b.png">

**Comment by amondnet** [comment]
> 로그인 화면 한글로 변경하려면 어떻게 하나요?

device 또는 simulator 의 언어 설정을 한글(Korean) 로 바꾸시면 됩니다.

> 화면 UI가 기본적으로 아래 UI인(첫번째 이미지) 것인가요?

네 카카오 sdk 에 제공하는 기본 UI 입니다. 

> 아래 두번째 화면 처럼 나오게 하려면 어떻게 하나요?

KakaoOpenSDK 의 KOSession.h 에
- <del>modalPresentationStyle </del> ( kakaoopensdk v1.19.0 이상 , 현재 [v1.17](https://github.com/JosephNK/flutter_kakao_login/blob/418338f9c46289c9ff0706a34e65734321acd268/ios/flutter_kakao_login.podspec#L18) 사용)
- @property (nonatomic, assign) UIBarStyle presentedViewBarStyle; // 웹뷰의 타이틀 바 스타일.
- @property (nonatomic, assign, getter=isPresentedViewBarTranslucent) BOOL presentedViewBarTranslucent;
- @property (nonatomic, strong) UIColor *presentedViewBarTintColor; // 웹뷰의 타이틀 바 색깔.
- @property (nonatomic, strong) UIColor *presentedViewBarButtonTintColor; // 웹뷰의 버튼 색깔.

이 있습니다.

> 제목도 logIn이 아닌 두번째 처럼 카카오 로그인 으로 변경하려면 어떻게 하나요?

device 또는 simulator 의 언어 설정을 한글(Korean) 로 바꾸시면 됩니다.
