### ISSUE TITLE
혹시 성별 정보 update 계획이 있으신지요?

### ISSUE THREAD

**Issue by developtkr** [JosephNK/flutter_kakao_login#28]
혹시 userme 에서 gender 정보를 받아오는 부분에 대한 업데이트 계획은 없으실까요?

소스를 받아서 kakaosdk 업데이트 후 수정하려했는데 정보를 받아오는데 어려움이 있네요 ㅠ

**Comment by JosephNK** [comment]
@developtkr 
확인 해보고 최대한 빠르게 업데이트 하도록 하겠습니다. ㅠ

**Comment by developtkr** [comment]
빠른답변 감사합니다..!
제가 어려움이 있었던 부분은
Gender 속성이 접근가능한지 체크한 후 정보를 받아오는 부분과
(이 부분은 sdk 가이드 그대로 적용하긴했습니다.)

getGender 메소드로 받아온 gender 값이 string이 아닌 enum 값이어서
account.getGender() == Gender.FEMALE ..
이런식으로 작업을 했었는데

계속 null값만 출력되는 문제가 있었습니다.

카카오 sdk에서는 성별정보에 대한 권한 및 사용 여부는 전부 체크 되어있었고,
로그인시에도 허용했었습니다.

좀 두서없는 설명이었지만 혹시 도움이  되실까 하여 말씀드립니다 ㅠ
감사합니다!

**Comment by JosephNK** [comment]
@developtkr 
늦었지만... 0.6.0 버전 업데이트 하면서 성별 가져오게 추가 하긴 하였는데...
저 또한 테스트시 Unknown으로만 나오더라구요... 흠...

**Comment by itnote** [comment]
public void requestMe(MethodChannel.Result result) {
    final MethodChannel.Result _result = result;

    List<String> keys = new ArrayList<>();
    keys.add("properties.nickname");
    keys.add("properties.profile_image");
    keys.add("properties.thumbnail_image");
    keys.add("kakao_account.email");

//   add
    keys.add("kakao_account.birthday");
    keys.add("kakao_account.gender");
    keys.add("kakao_account.age_range");

이부문 추가하면 성별,생일,나이 등등 잘 나옵니다.

**Comment by JosephNK** [comment]
아 그렇군요! 조만간 추가해서 업데이트 하도록 하겠습니다~ 고맙습니다 ^^

2020년 1월 28일 (화) 오후 7:12, itnote <notifications@github.com>님이 작성:

**Comment by developtkr** [comment]
최신 소스 받아서 itnote님이 지적해주신 부분 추가하니까 잘 받아지네요! 감사합니다 !!
@JosephNK
