### ISSUE TITLE
flutter_kakao_login conflict with multi_image_picker

### ISSUE THREAD

**Issue by kunkaamd** [JosephNK/flutter_kakao_login#32]
i got issue with https://pub.dev/packages/multi_image_picker and flutter_kakao_login. 
the function onActivityResult in multi_image_picker override so that function in flutter_kakao_login not working and that make crash app in android.
error in line => https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L575
because photos value is null.
i have change that and it working for me

`public class FlutterKakaoLoginPlugin implements FlutterPlugin, ActivityAware {

  private static final String CHANNEL_NAME = "flutter_kakao_login";

  private static final String LOG_TAG = "KakaoTalkPlugin";

  private static Registrar registrar;

  private Activity activity;
  private MethodChannel channel;
  private FlutterKakaoLoginHandler handler;

  /**
   * Plugin registration. for legacy Embedding API
   */
  public static void registerWith(Registrar registrar) {
    Activity activity = registrar.activity();
    if (activity == null) {
      return;
    }
    FlutterKakaoLoginPlugin.registrar = registrar;

    final FlutterKakaoLoginPlugin instance = new FlutterKakaoLoginPlugin();
    instance.onAttachedToEngine(registrar.messenger());
    instance.onAttachedToActivity(activity);
  }

  @Override
  public void onAttachedToEngine(FlutterPluginBinding flutterPluginBinding) {
    onAttachedToEngine(flutterPluginBinding.getBinaryMessenger());
  }

  private void onAttachedToEngine(BinaryMessenger messenger) {
    channel = new MethodChannel(messenger, CHANNEL_NAME);

  }

  @Override
  public void onDetachedFromEngine(FlutterPluginBinding binding) {
    channel.setMethodCallHandler(null);
    channel = null;
    handler = null;
  }

  @Override
  public void onAttachedToActivity(ActivityPluginBinding activityPluginBinding) {
    onAttachedToActivity(activityPluginBinding.getActivity());
    if(handler != null) {
      activityPluginBinding.addActivityResultListener(handler);
    }
  }

  private void onAttachedToActivity(Activity _activity) {
    activity = _activity;
    if (activity != null && channel != null) {
      handler = new FlutterKakaoLoginHandler(activity, channel);
      FlutterKakaoLoginPlugin.registrar.addActivityResultListener(handler);
      channel.setMethodCallHandler(handler);
    }
  }

  @Override
  public void onDetachedFromActivityForConfigChanges() {
    onDetachedFromActivity();
  }

  @Override
  public void onReattachedToActivityForConfigChanges(ActivityPluginBinding activityPluginBinding) {
    onAttachedToActivity(activityPluginBinding.getActivity());
    // after a configuration change.
  }

  @Override
  public void onDetachedFromActivity() {
    channel.setMethodCallHandler(null);
    activity = null;
    handler = null;
  }

}`

**Comment by JosephNK** [comment]
This issue was fixed in the multi_image_picker plugin. 
Note please. https://github.com/Sh1d0w/multi_image_picker/pull/514
