### ISSUE TITLE
구글 로그인 플러그인과 충돌

### ISSUE THREAD

**Issue by hwangjundong** [JosephNK/flutter_kakao_login#4]
샘플 pubspec.yaml에   google_sign_in: ^3.2.4 를 추가하면 앱이 죽습니다.

카카오로그인과 구글 버전 충돌이 나 빌드가 안되서, project level의 build.gradle에 아래와 같이 추가하니, 
빌드 오류는 나지 않습니다.
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.0.1"
            }
        }
    }
}

아래와 같은 노트가 나타나기는 하지만, 샘플만 돌렸을때 잘 동작합니다. 
Note: /.../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_kakao_login-0.0.5/android/src/main/java/com/josephnk/flutterkakaologin/FlutterKakaoLoginPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

왜 앱이 죽는지 원인을 모르겠네요?

**Comment by hwangjundong** [comment]
참. 안드로이드에서만 문제가 발생합니다.

**Comment by JosephNK** [comment]
@hwangjundong 

프로젝트에서 

android/build.gradle 파일

```
allprojects {
    repositories {
        google()
        jcenter()
    }
}
```
to
```
allprojects {
    repositories {
        configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '12.0.1'
                }
                if (requested.group == 'com.google.firebase') {
                    details.useVersion '12.0.1'
                }
            }
        }
        google()
        jcenter()
    }
}
```

위와 같이 변경해서 한번 해보셔요.

**Comment by hwangjundong** [comment]
되네요. ^^ 감사합니다. 

제가 안드로이드를 잘 몰라서 그러는데 이런 에러가 발생한 이유가 뭔가요?

**Comment by JosephNK** [comment]
@hwangjundong 

빈 프로젝트 생성해서... 
kakao플러그인과 google_sign 플러그인을 설치하여.. 
테스트 해보니 안드로이드 앱이 크래쉬 발생하길래..
크래쉬 확인 해보니, gms, firebase인 듯 해서.. 구글 검색으로 찾아봤어요.
그리고 google_sign_in과 사용했을 때....

```
Note: /.../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_kakao_login-0.0.5/android/src/main/java/com/josephnk/flutterkakaologin/FlutterKakaoLoginPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

이 부분은 안드로이드 스튜디오에서 FlutterKakaoLoginPlugin.java  파일에 대해서..
deprecated API 체크를 해봤는데.. not found인데... 왜 경고가 나오는지 모르겠네요...
추후 해당 부분은 좀 더 확인 해바야겠어요.

**Comment by hwangjundong** [comment]
네. 잘 배워 갑니다. ^^
감사합니다.
