### ISSUE TITLE
실제 배포된 버전에서 카카오톡앱 인증후 반응이 없습니다.

### ISSUE THREAD

**Issue by Farer** [JosephNK/flutter_kakao_login#40]
Google Play 에 배포하기 전 로컬 버전에서는 카카오톡앱을 통한 인증 후에 잘 진행이 됩니다.
하지만 배포한 후에 해당 버전을 Play Store 를 통해 설치하면 카카오톡 앱을 통해 인증한 후에 반환을 받지 못하는 것인지 진행이 안됩니다.
카카오톡 앱이 없는 경우 인증을 위한 카카오톡 로그인 페이지로 넘어가는데 이런 경우에는 인증이 진행됩니다.
이 부분 혹시 챙겨서 업데이트하실 수 있을까요?

관련 버전 정보도 추가합니다.

Flutter version 1.22.2
Platform android-30, build-tools 29.0.2
Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
VS Code (version 1.50.1)

**Comment by Farer** [comment]
혹시 무조건 웹페이지로만 인증이 가능하게 설정할 수 있어도 나쁘지는 않을 것 같습니다.

**Comment by JosephNK** [comment]
@Farer release apk로 테스트 해보았을 때, 카카오앱을 통해 인증 되는거 확인 했습니다. 혹시 debug apk가 아닌 release apk 에서 카카오앱을 통해 인증이 안된다는 말씀인가요?

**Comment by Farer** [comment]
> @Farer release apk로 테스트 해보았을 때, 카카오앱을 통해 인증 되는거 확인 했습니다. 혹시 debug apk가 아닌 release apk 에서 카카오앱을 통해 인증이 안된다는 말씀인가요?

말씀드린 대로 Play Store ( Android ) 와 App Store ( iOS ) 까지 실제 배포된 버전을 의미합니다.
배포되기 전에 로컬의 debug apk 와 release apk 등에서는 작동이 되어도 의미가 없지 않을까요?

**Comment by JosephNK** [comment]
> > @Farer release apk로 테스트 해보았을 때, 카카오앱을 통해 인증 되는거 확인 했습니다. 혹시 debug apk가 아닌 release apk 에서 카카오앱을 통해 인증이 안된다는 말씀인가요?
> 
> 말씀드린 대로 Play Store ( Android ) 와 App Store ( iOS ) 까지 실제 배포된 버전을 의미합니다.
> 배포되기 전에 로컬의 debug apk 와 release apk 등에서는 작동이 되어도 의미가 없지 않을까요?

음.. debug, release가 의미가 없진 않은 걸로 생각합니다만.. play store apk나 app store ipa가 따로 있는게 아니니깐요..
만약, release apk에서는 정상 작동하는데, play store에서 작동 되지 않는다면, 다른 이슈가 있는건지 알 수가 없네요.
