### ISSUE TITLE
Status hide the webview on S7

### ISSUE THREAD

**Issue by nguyenxuankiet262** [JosephNK/flutter_kakao_login#41]
![image](https://user-images.githubusercontent.com/38308481/100690955-3b7e5200-33ba-11eb-9c82-d5024f729dc2.png)

**Comment by JosephNK** [comment]
ref., https://devtalk.kakao.com/t/status-bar/109439/2 
```
<activity
        android:name="com.kakao.auth.authorization.authcode.KakaoWebViewActivity"
        android:theme="@android:style/Theme.NoTitleBar.Fullscreen"/>
```
@nguyenxuankiet262  couldn't checked it.. try it

**Comment by nguyenxuankiet262** [comment]
yes it worked but the status bar disappeared too
