### ISSUE TITLE
Null-safety support

### ISSUE THREAD

**Issue by beomjungil** [JosephNK/flutter_kakao_login#42]
Thanks for your awesome package.
Is there any plan in migrating to null-safety for Flutter 2.0.0?

Here's a kind guide about migrating. ([dart.dev](https://dart.dev/null-safety/migration-guide))

**Comment by JosephNK** [comment]
@beomjungil Thank you for your interest.
I just updated the null-safety migration version.

**Comment by beomjungil** [comment]
Thanks for your help.
I think we can close this issue.
