### ISSUE TITLE
Not getting continue with Kakao account 

### ISSUE THREAD

**Issue by KuldeepVagadiya** [JosephNK/flutter_kakao_login#43]
![Screenshot_20210401-121510](https://user-images.githubusercontent.com/76831502/113254585-6b941e00-92e4-11eb-8e6e-cbd34df1d526.jpg)

@JosephNK when click on continue button I am not getting any response from Kakao and I am stuck on this page, I tried different accounts but same problem 

NOTE:-- If KakaoTalk app installed in my device this page wont show up and I directly login with my KakaoTalk app it's only works on android version 10 or lower wont works on android version 11

@JosephNK  please let me know how to fix this problem, have a nice day.

**Comment by JosephNK** [comment]
@KuldeepVagadiya 

flutter_kakao_login: ^3.2.0

The latest Kakao SDK version (2.4.2) has been applied to the flutter_kakao_login package.
I think it's probably a Kakao SDK issue.

```
2.0.4
버그 수정   
Android 11 이상 타게팅 시 카카오톡 간편로그인 등 외부 패키지 사용 불가능 현상 대응
```
[https://developers.kakao.com/docs/latest/ko/sdk-download/android](https://developers.kakao.com/docs/latest/ko/sdk-download/android)

**Comment by DevKang** [comment]
@JosephNK 
저도 비슷한 이슈가 있습니다.
카카오 계정을 통해 로그인 시 계정 입력하고 [동의하고 계속하기] 버튼 활성화 후 누르더라도  웹뷰의 헤더 부분에서 "웹페이지 불러오는 중" 이라는 메세지만 뜨고 아무 반응이 없는 상태입니다.
현재 3.2.1버전 사용 중이며 사용 기기는 안드로이드 8.0 겔럭시 S7 사용 중입니다.

**Comment by JosephNK** [comment]
@DevKang 
제가 테스트시 [동의하고 계속하기] 클릭 후 넘어가지 않는 경우는, NATIVE_APP_KEY 설정과 AndroidMenifest.xml 설정 부분이 잘못 되었을 때 발생하였습니다.
이 부분 한번 확인 해보시면 될 것 같습니다. 
설정 부분 관련은 README 파일에 기재 되어 있으니 참고 바랍니다.

**Comment by DevKang** [comment]
@JosephNK 
AndroidMenifest.xml 에서 RedirectURI 의 NATIVE_APP_KEY를 제걸로 바꾸질 않았었습니다 ;;
기본적인 세팅인데 놓치고 질문드렸네요 ㅠ
혹시 저와 같은 실수를 하시는 분이 있을지도 모르니 질문은 남겨두겠습니다~!

빠르게 답변해주셔서 감사합니다 :)
