### ISSUE TITLE
카카오로그인시 crash 발생

### ISSUE THREAD

**Issue by kimjuggang** [JosephNK/flutter_kakao_login#46]
flutter_kakao_login 버전 2.0.0 사용중이고 kakao 로그인 요청시 crash 발생하며 아래는 로그입니다. 

첨부 로그 파일도 확인 부탁드립니다.

2021-05-09 11:14:13447 [💬][AuthController.swift 261:21] -> request: 
 url:https://kauth.kakao.com/oauth/authorize?client_id=6a9d527ad7be395e1ae764022fe8d78b&response_type=code&redirect_uri=kakao6a9d527ad7be395e1ae764022fe8d78b://oauth&ka=sdk/2.0.5%20sdk_type/swift%20os/ios-14.5%20lang/en-%20res/390x844%20device/iPhone%20origin/com.atop.AtopWallet%20app_ver/1.0.0
 parameters: ["client_id": "6a9d527ad7be395e1ae764022fe8d78b", "response_type": "code", "redirect_uri": "kakao6a9d527ad7be395e1ae764022fe8d78b://oauth", "ka": "sdk/2.0.5 sdk_type/swift os/ios-14.5 lang/en- res/390x844 device/iPhone origin/com.atop.AtopWallet app_ver/1.0.0"] 

2021-05-09 23:14:13.447439+0900 Runner[69952:365869] [AuthenticationSession] The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".
2021-05-09 23:14:13.497287+0900 Runner[69952:365869] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   AuthenticationServices              0x00007fff4aae1b15 -[ASWebAuthenticationSession initWithURL:callbackURLScheme:usingEphemeralSession:completionHandler:] + 684
	3   KakaoSDKAuth                        0x000000010a558680 $sSo26ASWebAuthenticationSessionC3url17callbackURLScheme17completionHandlerAB10Foundation3URLV_SSSgyAHSg_s5Error_pSgtctcfcTO + 272
	4   KakaoSDKAuth                        0x000000010a55770a $sSo26ASWebAuthenticationSessionC3url17callbackURLScheme17completionHandlerAB10Foundation3URLV_SSSgyAHSg_s5Error_pSgtctcfC + 74
	5   KakaoSDKAuth                        0x000000010a555087 $s12KakaoSDKAuth14AuthControllerC34authorizeWithAuthenticationSession8authType8agtToken6scopes16channelPublicIds12serviceTerms10completionyAA0cJ0OSg_SSSgSaySSGSgA2PyAA05OAuthL0VSg_s5Error_pSgtctF + 5143
	6   KakaoSDKAuth                        0x000000010a553462 $s12KakaoSDKAuth14AuthControllerC34authorizeWithAuthenticationSession8authType10completionyAA0cJ0OSg_yAA10OAuthTokenVSg_s5Error_pSgtctF + 114
	7   KakaoSDKAuth                        0x000000010a54a18f $s12KakaoSDKAuth7AuthApiC09loginWithA7Account8authType10completionyAA0cI0OSg_yAA10OAuthTokenVSg_s5Error_pSgtctF + 159
	8   Runner                              0x0000000107a222d7 $s19flutter_kakao_login28SwiftFlutterKakaoLoginPluginC5logIn33_BCF6E7FF794984D6DB86164008F15FECLL6resultyyypSgc_tF + 455
	9   Runner                              0x0000000107a216f9 $s19flutter_kakao_login28SwiftFlutterKakaoLoginPluginC6handle_6resultySo0E10MethodCallC_yypSgctF + 1321
	10  Runner                              0x0000000107a21fee $s19flutter_kakao_login28SwiftFlutterKakaoLoginPluginC6handle_6resultySo0E10MethodCallC_yypSgctFTo + 142
	11  Flutter                             0x0000000108abe3be __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	12  Flutter                             0x00000001082a4b26 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	13  Flutter                             0x00000001082a9878 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	14  Flutter                             0x00000001085f609f _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_33NS_9allocatorIS8_EEFvvEEclEv + 83
	15  Flutter                             0x00000001082b17b6 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 160
	16  Flutter                             0x00000001082b6526 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	17  CoreFoundation                      0x00007fff2039178a __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	18  CoreFoundation                      0x00007fff2039127c __CFRunLoopDoTimer + 924
	19  CoreFoundation                      0x00007fff2039081a __CFRunLoopDoTimers + 265
	20  CoreFoundation                      0x00007fff2038ae69 __CFRunLoopRun + 2013
	21  CoreFoundation                      0x00007fff2038a1a7 CFRunLoopRunSpecific + 567
	22  GraphicsServices                    0x00007fff2b874d85 GSEventRunModal + 139
	23  UIKitCore                           0x00007fff246c14df -[UIApplication _run] + 912
	24  UIKitCore                           0x00007fff246c639c UIApplicationMain + 101
	25  Runner                              0x00000001079413e8 main + 72
	26  libdyld.dylib                       0x00007fff2025abbd start + 1
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".'
CoreSimulator 757.5 - Device: iPhone 12 (0A63FBF7-6EE7-42CE-96A1-AA8AAC0744E4) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 12
terminating with uncaught exception of type NSException
(lldb) [
[attachment.crashlog-3A2C2A85-CB45-4A38-A551-03EECA98F96E.txt](https://github.com/JosephNK/flutter_kakao_login/files/6447708/attachment.crashlog-3A2C2A85-CB45-4A38-A551-03EECA98F96E.txt)
](url)

**Comment by JosephNK** [comment]
해당 이슈는 아래 이슈와 동일한 이슈로 판단 됩니다. 참고 바랍니다.
[#47](https://github.com/JosephNK/flutter_kakao_login/issues/47) 카카오톡이 설치되지 않은 기기에서의 오류
