### ISSUE TITLE
카카오톡이 설치되지 않은 기기에서의 오류

### ISSUE THREAD

**Issue by LOCKEDFILE** [JosephNK/flutter_kakao_login#47]
https://devtalk.kakao.com/t/ios-14-5-2/115366

카카오톡을 설치하지 않은 기기에서 종료가 되고 있습니다.  
위의 링크에서는 sdk 버전을 업데이트 하면 된다고 하네요.
혹시 업데이트 가능할까요?

 

~~~
The provided scheme is not valid. A scheme should not include special characters such as “:” or “/”.
~~~

**Comment by JosephNK** [comment]
@LOCKEDFILE iOS sdk 버전 올려야겠네요. 확인해보겠습니다.

**Comment by JosephNK** [comment]
@LOCKEDFILE KAKAO SDK For iOS 2.5.2로 업데이트 하였습니다. 확인 부탁 드립니다. 
```
flutter_kakao_login: ^3.3.0
```

**Comment by LOCKEDFILE** [comment]
빠른 수정 감사합니다.!! :)
