### ISSUE TITLE
아이고 선생님 static frameworks: (KakaoOpenSDK) 여기에 문제가 발생합니다.

### ISSUE THREAD

**Issue by show1111** [JosephNK/flutter_kakao_login#5]
`
$ pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
Fetching podspec for `flutter_kakao_login` from `.symlinks/plugins/flutter_kakao_login/ios`
Fetching podspec for `flutter_pedometer` from `.symlinks/plugins/flutter_pedometer/ios`
Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
Fetching podspec for `share` from `.symlinks/plugins/share/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
Downloading dependencies
Using Bolts (1.9.0)
Using FBSDKCoreKit (4.40.0)
Using FBSDKLoginKit (4.39.1)
Using Firebase (5.16.0)
Using FirebaseAnalytics (5.5.0)
Using FirebaseAuth (5.3.0)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (5.2.0)
Using FirebaseInstanceID (3.4.0)
Using Flutter (1.0.0)
Using GTMSessionFetcher (1.2.1)
Using GoogleAppMeasurement (5.5.0)
Using GoogleSignIn (4.4.0)
Using GoogleToolboxForMac (2.2.0)
Using GoogleUtilities (5.3.7)
Installing KakaoOpenSDK (1.11.1) <------------
Using Reachability (3.2)
Using connectivity (0.0.1)
Using device_info (0.0.1)
Using firebase_auth (0.0.1)
Using firebase_core (0.0.1)
Using flutter_facebook_login (0.0.1)
Installing flutter_kakao_login (0.0.6) <-----------------
Using flutter_pedometer (0.0.1)
Using fluttertoast (0.0.2)
Using google_sign_in (0.0.1)
Using nanopb (0.3.901)
Using package_info (0.0.1)
Using permission_handler (2.1.2)
Using share (0.5.2)
Using shared_preferences (0.0.1)
Using video_player (0.0.1)
[!] The 'Pods-Runner' target has transitive dependencies that include static frameworks: (KakaoOpenSDK)

[!] 'KakaoOpenSDK' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safenetwork with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.`

이게 문제드라구요.
[!] The 'Pods-Runner' target has transitive dependencies that include static frameworks: (KakaoOpenSDK)

use_frameworks! 요걸 제거 하고도 해봤는데 이걸 해버리면 다른것들이 전부 박살나드라구요...

이리 저리 많이 찾아 보고 있는데.. 도와주세요.

**Comment by JosephNK** [comment]
@show1111 
podspec에 static_framework = true 추가해서 업데이트 하였습니다.
한번 업데이트 된 버전으로 해보시겠어요?
[static_framework = true](https://github.com/JosephNK/flutter_kakao_login/commit/037fe27952d1860c08ecd11b8d71fd56a8ad3229)

**Comment by show1111** [comment]
업데이트 받아도 작동 안되더라구요 ㅠㅠ 
근디 현재 플러터 패키지 페이지에서 카카오 검색이 안되고 있어요..이건 무슨일인지 잘 모르겟어요
일단 use_frameworks 요거 제거 하고 문제 터지는 플러그인들 전부 막고.
작동 확인 했습니다. ㅠㅠ  혹시 카카오링크는 포함 안되어 있는 버전이시죠?

**Comment by JosephNK** [comment]
@show1111
0.0.7 버전으로 설치 하고, use_frameworks 지우지 않고 해도 안되던가요?
카카오 SDK안에 카카오링크도 포함되어 있을텐데... flutter로 링크는 따로 구현은 안했습니다.
음.. 그리고 확인해보니 flutter pubs에서 all 해야지만 flutter_kakao_login 플러그인이 검색이 되네요...
이 부분은 문의를 해봐야겠네요. ㅠ.ㅠ 
https://pub.dartlang.org/packages/flutter_kakao_login

**Comment by show1111** [comment]
아이고 선생님 잘 작동합니다. 
안드로이드는 혹시 androidX 포함 된건가요...x 버전이 충돌이 나드라구요 전 안드로이드는 0.0.5 버전을 쓰고 ios 최신으로 유지하고 있습니다.
우짜든 고생이 많으시네요. 저두 adbrix 플러그인 만들고 있습니다만.. 만만치 않네요 ㅠㅠ

**Comment by JosephNK** [comment]
@show1111 
Android X는 테스트 어떻게 하나요? 
플러그인 만들 때, 따로 X를 위해 설정이 있는건가요?
해당 플러그인 경우에... 안드로이드 build.gradle 확인 해보니...
```
complieSdkVersion 27
minSdkVersion 16
```
이렇게 설정 되어 있습니다.
참고로 flutter github에서 Android X에 대해 검색해보니 아래와 같은 이슈가 있나봐요..
https://github.com/flutter/flutter/issues/27792

**Comment by JosephNK** [comment]
@show1111 
https://pub.dartlang.org/flutter/packages?q=flutter_kakao_login
pubs에서 해당 플러그인 검색 안되신다고 하셨던거 확인 해보니 이제 잘 나오네요.
참고로 제가 따로 한 건 없습니다. ^^;

**Comment by show1111** [comment]
테스트라기 보다 빌드 할때 에러가 발생하는데 androidX.method 메소드가 보여요 아 그래서 이버전은 쓰면 안되겟구나 이러고 있습니다. 이게  골때리는게 플러그인을 수십개 쓰는데 전부 처리가 안되믄 문제가 생기는듯 합니다.  그리고 로그라도 보여드릴라고 다시 해봤는데 에러가 안나요 ㅠㅠ 플러그인이 너무 많아서 이걸루 착각했나봐요 ㅠㅠ

**Comment by show1111** [comment]
아 저두 하나 올려 봤는데 올리고 시간이 좀 지나야 검색이 되더라구요.. 그리고 패키지 다운 받는 사이트 플러그인 검색 기능이 완전 구려요. 라인 로그인 검색 한적 잇는데 정확하게 flutter_line_login 이래야 나오드라구요 ㅠㅠ

**Comment by JosephNK** [comment]
@show1111 
pubs에 검색 부분 관련 해서...  현재 이슈가 있는 듯 합니다.
참고로 링크 하나 걸어드릴께요 ^^
https://github.com/dart-lang/pub-dartlang-dart/issues/2057

**Comment by show1111** [comment]
아이구 감사합니다. 만수무강하시고 하시는 일 대박나시길 
그리고 하다보니 터득한 방법인데 
 프로젝트  ios/.symlinks/plugins/해당플러그인/ios/해당플러그인.podspec   파일에 직접 static_framework = true  넣어서 해결 보고 있습니다. ^^

**Comment by JosephNK** [comment]
@show1111 
네 감사합니다. ^^ 화이팅하시고 늦었지만 새해 복 많이 받으세요. :)
