### ISSUE TITLE
Android kakao sdk version issue due to SSL certificate substitution

### ISSUE THREAD

**Issue by leejh10003** [JosephNK/flutter_kakao_login#50]
좋은 라이브러리 만들어 주셔서 감사합니다. 카카오 인증서 이슈에 대해 말씀드릴 내용이 있습니다.

신뢰의 고리 문제로 인해, 애플이 카카오가 사용하고 있는 시만텍 발 인증서를 루트 저장소에서 삭제할 예정입니다. 이에 따라 카카오는 자사 도메인 일부의 SSL 인증서를 변경하기로 결정했습니다. 영향을 받는 도메인은 다음과 같습니다:

- kauth.kaka.com
- kapi.kakao.com
- dapi.kakao.com

카카오는 2021/10/1에 인증서를 교체할 예정입니다. 이후 지원되는 카카오 SDK 버전은 다음과 같습니다:
- iOS SDK 2.x
- Android SDK 2.7.0+

문제가 되는 부분이 있는지 확인 부탁드립니다. 감사합니다!

본 이슈에 대한 최대한 많은 유저의 접근성을 위해, 영어로 다시 질문을 첨부하겠습니다.

Thank you for creating a great library! I want to discuss Kakao's recent certificate issue.

Due to a chain of trust problem, Apple will delete Symantec certificate Kakao corp is currently using, so Kakao corp will substitute their domains' SSL certificate. Following domains will be effected:

kauth.kakao.com
kapi.kakao.com
dapi.kakao.com
They will change the certificate on 10/1/2021. And here's the supported Kakao SDK version after then:

iOS SDK 2.x
Android SDK 2.7.0+
Please check if there would be an issue. Thank you!

**Comment by JosephNK** [comment]
@leejh10003 감사합니다. 확인 해보겠습니다.

**Comment by JosephNK** [comment]
@leejh10003 KAKAO SDK 업데이트 했습니다. CHANGELOG.md 파일 확인해주세요. 감사합니다. :)
```
dependencies:
  flutter_kakao_login: ^3.4.0
```

**Comment by leejh10003** [comment]
감사합니다~! 본 이슈는 제가 코멘트를 달고 클로즈 하도록 하겠습니다. 10월 1일 이후 문제가 다시 발생한다면 알려드리거나 해결 도와드리겠습니다!
