### ISSUE TITLE
안녕하세요? 제가 플러터 앱에 카카오 로그인 연동하는데 이런 오류가 나오다라고요. 뭘 잘 못 한 거죠?

### ISSUE THREAD

**Issue by chinzorigts** [JosephNK/flutter_kakao_login#51]
PlatformException(LOGIN_ERR, 로그인 실패, invalid android_key_hash or ios_bundle_id or web_site_url, null)

**Comment by JosephNK** [comment]
invalid android_key_hash or ios_bundle_id or web_site_url

**Comment by chinzorigts** [comment]
그럼 이거를 어떻게 수정 하면 될까요?

**Comment by JosephNK** [comment]
해당 에러가 무엇인지 파악을 해보세요.

**Comment by ricky-o-k** [comment]
https://github.com/JosephNK/flutter_kakao_login/issues/51#issuecomment-913410448

`invalid android_key_hash or ios_bundle_id or web_site_url` 에 대해 검색해보시면 될 것 같네요
