### ISSUE TITLE
.logIn()이후 반응이 없습니다.

### ISSUE THREAD

**Issue by taeilyoon** [JosephNK/flutter_kakao_login#54]
await 를 걸고 login을 할경우 ios 에서 응답이 오지 않습니다.

카카오 톡으로 넘어가지고 인증버튼을 누를뒤   앱으로 돌아오고 나서도 응답이 오지 않습니다.

<img width="566" alt="스크린샷 2021-11-10 17 56 00" src="https://user-images.githubusercontent.com/23698016/141081666-84022b2b-abdc-4a59-899a-99f8a1870e6a.png">

해당 코드의 48번 줄이 실행 안되는 것을 보아 ios 네이티브에서 반환을 못하는거 같습니다.

**Comment by JosephNK** [comment]
README파일에 나와있는 설정과 카카오 개발자 사이트 설정을 한번 확인 해봐주세요.
정확히 어떤 현상인지 알 수가 없네요.

**Comment by JosephNK** [comment]
https://github.com/JosephNK/flutter_kakao_login/issues/55#issuecomment-999259224 해당 코멘트도 참고 해보세요.
