### ISSUE TITLE
해시코드 받아오고 .login() 시 앱이 그냥 종료됩니다.

### ISSUE THREAD

**Issue by Kimhyunsu92** [JosephNK/flutter_kakao_login#55]
![스크린샷 2021-11-18 오전 8 22 31](https://user-images.githubusercontent.com/91927059/142298395-7690153c-602a-4cf3-ae07-7385a9294701.png)
혹시 이부분에 대해서 해결할 수 있는 방법이 있을까요?

**Comment by JosephNK** [comment]
README파일에 나와있는 설정과 카카오 개발자 사이트 설정을 한번 확인 해봐주세요.
저도 해당 플러그인을 프로젝트에서 사용중인데, 이슈를 발견하지 못했어요.

**Comment by Kimhyunsu92** [comment]
감사합니다. 해당 이슈는 프로젝트에 패키지 충돌문제 였습니다!

**Comment by JosephNK** [comment]
해결 되었다니 다행이네요. :)
