### ISSUE TITLE
final result = await kakaoSignIn.logIn(); 응답이 돌아오지 않습니다.

### ISSUE THREAD

**Issue by betternormal** [JosephNK/flutter_kakao_login#56]
카카오 로그인화면 띄우고, 로그인 누르면 그상태로 멈춰있습니다.
해당코드는 작성한 개발자쪽에서는 실행되는 상황입니다.

**Comment by JosephNK** [comment]
README파일에 나와있는 설정과 카카오 개발자 사이트 설정을 한번 확인 해봐주세요.
정확히 어떤 현상인지 알 수가 없네요.

**Comment by JosephNK** [comment]
https://github.com/JosephNK/flutter_kakao_login/issues/55#issuecomment-999259224 해당 코멘트도 참고 해보세요.
