### ISSUE TITLE
사용자 관리 - 개인 정보 보호 항목에 '카카오계정(이메일)'이 선택되지 않았을 경우 Exception이 발생합니다.

### ISSUE THREAD

**Issue by JHK88** [JosephNK/flutter_kakao_login#7]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.kakao.usermgmt.response.model.UserAccount.getEmail()' on a null object reference
E/AndroidRuntime(17048): 	at com.josephnk.flutterkakaologin.FlutterKakaoLoginPlugin$SessionCallback$1.onSuccess(FlutterKakaoLoginPlugin.java:240)
E/AndroidRuntime(17048): 	at com.josephnk.flutterkakaologin.FlutterKakaoLoginPlugin$SessionCallback$1.onSuccess(FlutterKakaoLoginPlugin.java:220)
E/AndroidRuntime(17048): 	at com.kakao.network.callback.ResponseCallback.onSuccessForUiThread(ResponseCallback.java:76)
E/AndroidRuntime(17048): 	at com.kakao.network.tasks.KakaoResultTask$1$1.run(KakaoResultTask.java:78)
E/AndroidRuntime(17048): 	at android.os.Handler.handleCallback(Handler.java:789)
E/AndroidRuntime(17048): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime(17048): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(17048): 	at android.app.ActivityThread.main(ActivityThread.java:6940)
E/AndroidRuntime(17048): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17048): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(17048): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by JosephNK** [comment]
@JHK88 확인 해보겠습니다~

**Comment by JosephNK** [comment]
@JHK88 
수정해서 업데이트 하였습니다.
제가 테스트 할 때는 발생 하지 않았는데.. 혹시나 해서 아래와 같이 수정하였습니다.
확인 부탁 드리겠습니다.
감사합니다.
[- fixed getEmail null exception for android.](https://github.com/JosephNK/flutter_kakao_login/commit/a92c8634dcb2bbd5cca0339daea65f58b04762ea)

**Comment by JosephNK** [comment]
This issue has no response and closes.

**Comment by GwonHyeok** [comment]
@JosephNK 

이메일 사용 설정을 안했을때 다음과 같이 에러가 여전히 발생 합니다.

`java
final String userEmail = (resultKakao.getKakaoAccount().getEmail() == null) ? "" : resultKakao.getKakaoAccount().getEmail();
`

getKakaoAccount() 가 null 이라 에러가 발생합니다.

이해를 돕기 위해 로그켓 내용도 같이 첨부합니다.

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.kakao.usermgmt.response.model.UserAccount.getEmail()' on a null object reference
	at com.josephnk.flutterkakaologin.FlutterKakaoLoginPlugin$SessionCallback$1.onSuccess(FlutterKakaoLoginPlugin.java:240)
	at com.josephnk.flutterkakaologin.FlutterKakaoLoginPlugin$SessionCallback$1.onSuccess(FlutterKakaoLoginPlugin.java:220)
	at com.kakao.network.callback.ResponseCallback.onSuccessForUiThread(ResponseCallback.java:76)
	at com.kakao.network.tasks.KakaoResultTask$1$1.run(KakaoResultTask.java:78)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:209)
	at android.app.ActivityThread.main(ActivityThread.java:7021)

E/AndroidRuntime(18898): 	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
