### ISSUE TITLE
화면 겹침 현상

### ISSUE THREAD

**Issue by baeharam** [JosephNK/flutter_kakao_login#8]
이게 제 문제인지 모르겠는데, 카카오 연동만 시키면 로그인 하는 순간 화면이 한번 더 나타나는데 원래 그런건가요?

**Comment by JosephNK** [comment]
@baeharam 
답변이 늦었네요.. 화면이 한번 더 나타난다는게 어떤 현상인지 모르겠으나...
flutter_kakao_login 플러그인 경우, UI 요소를 사용하는게 없어요. 
Back단 처리만 하는거라... UI 부분에 대해서는 잘 모르겠네요...

**Comment by JosephNK** [comment]
This issue has no response and closes.
